[package]
name = "launcher"
version = "0.1.0"
authors = ["Dorian Rudolph <dorian@mail.upb.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freedesktop_entry_parser = "1.0.0"
locale-types = "0.4.0"
pathsearch = "0.2.0"
libc = "0.2.74"
gtk-layer-shell = { path = "../gtk-layer-shell-rs" }
gtk = "0.9.1"
gio = "0.9.0"
gdk = "0.13.0"