[package]
name = "launcher"
version = "0.1.0"
authors = ["Dorian Rudolph <dorian@mail.upb.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freedesktop_entry_parser = "1.0.0"
locale-types = "0.4.0"
pathsearch = "0.2.0"
libc = "0.2.74"
gtk-layer-shell = { path = "../gtk-layer-shell-rs" }
gtk = { version = "0.9.1", features = ["v3_22"] }
gio = "0.9.0"
gdk = "0.13.0"
pango = "0.9.0"
shellexpand = "2.0.0"
gdk-pixbuf = "0.9.0"
env_logger = "0.7.1"
log = "0.4.11"
glib = "0.10.1"
futures = "0.3.5"