[package]
name = "launcher"
version = "0.1.0"
authors = ["Dorian Rudolph <dorian@mail.upb.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
locale-types = "0.4.0"
pathsearch = "0.2.0"
libc = "0.2.74"
gtk-layer-shell = { path = "../gtk-layer-shell-rs" }
gtk = { version = "0.9.1", features = ["v3_22"] }
gio = "0.9.0"
gdk = "0.13.0"
pango = "0.9.0"
gdk-pixbuf = "0.9.0"
glib = "0.10.1"
futures = "0.3.5"
fuzzy-matcher = "0.3.5"
xdg = "2.2.0"
serde = "1.0.114"
serde_derive = "1.0.114"
toml = "0.5.6"