# This config file serves as documentation and contains the default values. You are free to omit all values.

side = "right"  # appear "left" or "right" on the screen
exclusive = "true"  # push all windows aside or appear above existing windows
icon_size = 64
lines = 2  # maximum number of lines of app labels

# markup for app labels
# it seems impossible to theme only parts of a label with CSS
# therefore, we need to use pango directly
# you can use all attributes of the <span> tag (https://developer.gnome.org/pygtk/stable/pango-markup-language.html)
markup_default = ''
# the executable is appended to the app name if it is not contained (e.g., evince calls itself just "Document Viewer")
markup_exe = 'font_style="italic" font_size="smaller"'
markup_highlight = 'foreground="red" underline="double"'  # highlight matched characters